FROM fedora:latest
RUN dnf install -y httpd \
    && dnf clean all \
    && dnf remove vim tuxpaint
RUN touch /var/www/html/my-info.html \
    && echo "Assignment4" >> /var/www/html/my-info.html

COPY /data /var/www/html/data

EXPOSE 80
CMD apachectl -D FOREGROUND
